version: "3.7"

services:
  angular:
    hostname: localhost
    container_name: angular-container
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    ports:
      - 80:4200
    volumes:
      - .:/app
